version: 0.2

phases:
  pre_build:
    commands:
     - nuget.exe restore
     - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
     - dpkg -i packages-microsoft-prod.deb
     - apt-get update
     - add-apt-repository universe
     - apt-get install -y powershell
     - pwsh
     - pwsh -Command
  build:
    commands:
     - msbuild .\WireTap\WireTap.csproj

artifacts:
  files:
   - '**/*'
  base-directory: '.\OutputPackage'