version: 0.2

phases:
  pre_build:
    commands:
      - nuget.exe restore
      - pwsh -Command 'Set-MpPreference -DisableRealtimeMonitoring $true'
      - pwsh -Command 'Set-MpPreference -MAPSReporting Disabled'
      - pwsh -Command 'Set-MpPreference -SubmitSamplesConsent NeverSend'

  build:
    commands:
     - msbuild .\WireTap\WireTap.csproj

artifacts:
  files:
   - '**/*'
  base-directory: '.\OutputPackage'