version: 0.2

phases:
  pre_build:
    commands:
      - nuget.exe restore
      

  build:
    commands:
     - powershell.exe -command 'Set-MpPreference -ExclusionPath C:\'
     - powershell.exe -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
     - powershell.exe -command 'Set-MpPreference -MAPSReporting Disabled'
     - powershell.exe -command 'Set-MpPreference -SubmitSamplesConsent NeverSend'
     - msbuild .\WireTap\WireTap.csproj

artifacts:
  files:
   - '**/*'
  base-directory: '.\OutputPackage'