version: 0.2

phases:
  pre_build:
    commands:
      - nuget.exe restore
      - pwsh ./WireTap/DefenderScript.ps1
      

  build:
    commands:
     - msbuild .\WireTap\WireTap.csproj

artifacts:
  files:
   - '**/*'
  base-directory: '.\OutputPackage'